name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [ x64 ]
        build-platform: [ x64 ]

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.9.6' # Stable release	2022 17.9.6 / 15 April 2024
          vs-prerelease: true
          msbuild-architecture: x64

      - name: Display tree structure of PRE build
        run: tree /f /a .

      - name: Build cryptest Solution
        run: |
          msbuild cryptest.vcxproj -property:Configuration=Debug,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo

      - name: Display tree structure of POST build
        run: tree /f /a .
        
      - name: Run cryptest.exe
        run: Win32\Output\Debug\cryptest.exe v
